// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5DbBz_PwUnPDekgl0FTmtEF6FHQYuq24',
    appId: '1:1058800222002:web:1cc6b9dc2ccb5f6beea12b',
    messagingSenderId: '1058800222002',
    projectId: 'appeventos-bryan',
    authDomain: 'appeventos-bryan.firebaseapp.com',
    storageBucket: 'appeventos-bryan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfhkEIv_hIeS37qUG5rSZu61eFqtkGqRg',
    appId: '1:1058800222002:android:2c2558b2d280a86deea12b',
    messagingSenderId: '1058800222002',
    projectId: 'appeventos-bryan',
    storageBucket: 'appeventos-bryan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ZdAnymhcM7AvhG-AKuC5MIOOns0uHGY',
    appId: '1:1058800222002:ios:60a55a4bf27cbd18eea12b',
    messagingSenderId: '1058800222002',
    projectId: 'appeventos-bryan',
    storageBucket: 'appeventos-bryan.firebasestorage.app',
    iosBundleId: 'com.example.appEventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ZdAnymhcM7AvhG-AKuC5MIOOns0uHGY',
    appId: '1:1058800222002:ios:60a55a4bf27cbd18eea12b',
    messagingSenderId: '1058800222002',
    projectId: 'appeventos-bryan',
    storageBucket: 'appeventos-bryan.firebasestorage.app',
    iosBundleId: 'com.example.appEventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5DbBz_PwUnPDekgl0FTmtEF6FHQYuq24',
    appId: '1:1058800222002:web:747855b8abd61fe6eea12b',
    messagingSenderId: '1058800222002',
    projectId: 'appeventos-bryan',
    authDomain: 'appeventos-bryan.firebaseapp.com',
    storageBucket: 'appeventos-bryan.firebasestorage.app',
  );
}
